### PR TITLE
Include rapidjson in the package

### PR DESCRIPTION
**Pull request by bioothod**
Rapidjson is required by eblob and elliptics which depend on handystats to provide it like it did before

### CODE REVIEW

**Comment by shindo** [comment]
Hi!

The request sounds odd to me, we removed usage of RapidJSON from handystats API long time ago: https://github.com/yandex/handystats/pull/17

If elliptics and/or eblob still require RapidJSON, it is not because of handystats dependency.
You should just add RapidJSON as submodule to elliptics/eblob.

**Comment by bioothod** [comment]
handystats carried rapidjson in its include project dir quite for a while and others depended on that, it was not about public interfaces which exported rapidjson classes. You still carry it in third-party artefacts, but do not want to expose in public include dir, don't you?

**Comment by shindo** [comment]
>handystats carried rapidjson in its include project dir quite for a while

Because we had public functions that use RapidJSON types.

>it was not about public interfaces which exported rapidjson classes

Are you sure about that? I don't remember such an agreement.

>You still carry it in third-party artefacts, but do not want to expose in public include dir, don't you?

This will limit us to update and/or replace RapidJSON as it will break dependent projects.
And this is odd restriction as we don't use RapidJSON in our public API.

What is the problem with RapidJSON submodule in your project?
BTW, you can use this RapidJSON packaging: https://github.com/shindo/librapidjson

**Comment by bioothod** [comment]
Problem is, there is a number of other packages which depended on handystats carrying and exporting rapidjson which it did for years, you decided to end this (probably long ago).
Everything can be rewritten, replaced or changed, this pull request was about making others happy with the least efforts, but it looks like this contradicts with your vision of handystats and you are against these changes, aren't you?

**Comment by shindo** [comment]
No, I'm OK with providing RapidJSON headers if this is the simplest solution for your problem and you ask to help you.

Are you sure that RapidJSON version that we use is suitable for your project?
In the commit where we moved to RapidJSON submodule we updated RapidJSON version (to v1.0) and that required us to update our code: https://github.com/yandex/handystats/commit/afb323b5ce9fbf1cf05dfe31cd19e995a1416861

**Comment by bioothod** [comment]
Yes, your submodule's checkout works good, I had to update the other code, but it was needed anyway for a long time to catch up with the modern systems. Please then merge this pull request, if you think everything is ok

**Pull request merged**
