### PR TITLE
Remove hardcoded rapidjson library.

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**
Remove the hardcoded rapidjson and use a release >= 1.0.0 with a stable API.

### CODE REVIEW

**Comment by shindo** [comment]
Thanks for the contribution!

You're right, there's no point to provide a copy of rapidjson (v0.11 or so). Before rapidjson v1 there were no such packages (for Ubuntu/RHEL/Arch), so we just copied some version of it.
And providing these sources as part of handystats public headers was kind of a mistake (this has led to unnecessary dependencies that are hard to get rid of now).

But were did you get `rapidjson-dev` package for Ubuntu? It has only 0.12: http://packages.ubuntu.com/source/rapidjson

I think it's better to use "private" submodule right now, i.e. use it to compile handystats sources only and leave rapidjson v1 includes in public headers as is, so the user should install rapidjson v1 by themself (via submodule, package or a plain copy) and add it to include path.

BTW, I tried to package rapidjson v1 here: https://github.com/shindo/librapidjson

**Comment by Romain-Geissler-1A** [comment]
Actually I haven't tried any of the packet manager that I have modified in this pull request. For each of them, I tried to find out the name of the packet in the corresponding distro. For .deb I looked in the Debian repository, not Ubuntu: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=rapidjson But I have just realized than the rapidjson provided by Debian testing/unstable is too old (experimental is up to date though)... It looks like Ubuntu and Debian have diverged on the "rapidjson" packet.

In our case, we work with a kind of a proprietary packet manager that I can't disclosed. We just install rapidjson include folder somewhere, then when building handystats we just pass the "-DDRAPIDJSON_INCLUDE_DIRS" flags to the initial cmake configure command.

The reason why we have developed this pull request is that we had conflicting rapidjson definitions between the one using the latest version 1.0.2 we already have packaged and the one that is currently provided by handystats that uses an older version.

Tell me if I am wrong. You suggest I keep this current implementation for finding rapidjson (with "find_package", then fallbacking on the RAPIDJSON_INCLUDE_DIRS environment variable) but add another fallback mechanism which would look in a "./rapidjson" subdirectory where anyone is free to copy/git clone the rapidjson sources ?

**Comment by shindo** [comment]
Alright after consideration I suggest the following.

CMake variable `RAPIDJSON_INCLUDE_DIR` could be specified to provide a directory where RapidJSON headers are installed (e.g. `/usr/include` or `/usr/local/include`, but not `/usr/include/rapidjson`).

If this variable is specified it's added to `INCLUDE_DIRECTORIES`.
Otherwise, ```FIND_PACKAGE (RapidJSON REQUIRED)``` is used to find RapidJSON.

And you should not add `rapidjson-dev` package as a dependency.

**Comment by Romain-Geissler-1A** [comment]
Closing since upstream seems to have removed rapidjson now.

**Pull request closed without merging**
